run_tests:
  image: python:3.10.6-slim-buster
  before_script:
    - pip install -r requirements.txt
  script:
    - python -m pytest tests/

build_image:
  image: docker:20.10.17
  services:
    - docker:20.10.17-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    IMAGE_NAME: solutiondev246/product-owners-app
    IMAGE_TAG: python-app-1.0
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG