stages:
  - test
  - build
  - deploy

run_tests:
  stage: test
  image: python:3.10.6-slim-buster
  before_script:
    - pip install -r requirements.txt
  script:
    - python -m pytest tests/

build_image:
  stage: build
  image: docker:20.10.17
  services:
    - docker:20.10.17-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    IMAGE_NAME: solutiondev246/product-owners-app
    IMAGE_TAG: python-app-1.0
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy
  before:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY root@188.166.158.107 "
        docker login -u $REGISTRY_USER -p $REGISTRY_PASS &&
        docker ps -aq | xargs docker stop | xargs docker rm &&
        docker run -d -p 5000:5000 $IMAGE_NAME:$IMAGE_TAG"